manifest:
  remotes:
    - name: marschelloss
      url-base: https://github.com/Marschelloss
  projects:
    - name: zmk
      remote: marschelloss
      revision: mouse-softoff
      import: app/west.yml
  self:
    path: config
