manifest:
  remotes:
    - name: marschelloss
      url-base: https://github.com/Marschellos
  projects:
    - name: zmk
      remote: marschelloss
      revision: mouse+softoff
      import: app/west.yml
  self:
    path: config
